### PR TITLE
[CS2] Update iloopmode.h, and irecipientfilter.h

### PR DESCRIPTION
**Pull request by hzqst**
Pretty much the title.

### CODE REVIEW

**Comment by GAMMACASE** [comment]
I see that you reverted back the header split, can I know why? The loop stuff is still better to be in its own header file

**Comment by hzqst** [comment]
> I see that you reverted back the header split, can I know why? The loop stuff is still better to be in its own header file

Because I did a full copy-paste from @psychonic 's dwarf bin results which didn't do the division.

**Comment by GAMMACASE** [comment]
Yea, but his work shouldn't be treated as a goto/state of the art one, he just shared what he had laying around, and as per his comment as well, this needs to be moved to a separate header file.

**Comment by GAMMACASE** [comment]
Looks good now, thanks for the contribution!

**Pull request merged**
