### PR TITLE
Portal 2 SDK adjustments

### PR DESCRIPTION
**Pull request by InputEvelution**
Made some changes to the Portal 2 SDK required to fix issues with the SPT plugin for Portal 2.

### CODE REVIEW

**Comment by psychonic** [comment]
Those IVEngineServer changes are not correct. Those functions do not exist on that interface in Portal 2.

**Comment by psychonic** [comment]
Looking more at what you're trying to do, it appears that you're trying to port https://github.com/YaLTeR/SourcePauseTool to Portal 2.

We generally don't support the client-side area of the SDK due to us having no use for them, and their primary usage being for cheats (which I'm aware SPT is not). I don't see any harm in taking that iface version name change though.

For PEntityOfEntIndex and IndexOfEdict, you'll need to get them differently since the functionality is not exposed on the engine interface in Portal 2 (or any Valve game beginning with L4D). Instead use something like https://github.com/alliedmodders/sourcemod/blob/master/public/compat_wrappers.h#L125

**Comment by InputEvelution** [comment]
Changed eiface.h to how it was beforehand. Apologies for not researching further into this beforehand. Thanks for the help.

**Comment by psychonic** [comment]
You still have a change there on eiface.h. I think you may have changed the encoding.

Another thing of note for IVEngineClient: usually when they bump the interface version numbers, they've also added or removed functions. Depending on where in the order and what functions, and which one(s) you use, you may require further changes.

**Comment by theKlaxon** [comment]
what all would i have to do to this sdk to get it working with portal 2?

**Comment by psychonic** [comment]
Closing due to inactivity.

**Pull request closed without merging**
