### PR TITLE
[L4D2] Update KeyValues

### PR DESCRIPTION
**Pull request by A1mDev**

### CODE REVIEW

**Review by psychonic — APPROVED** [review]

**Comment by jensewe** [comment]
"exprevaluator.h" is missing.

**Comment by psychonic** [comment]
> "exprevaluator.h" is missing.

Thanks. Handled in https://github.com/alliedmodders/hl2sdk/commit/487ed6af40395548c99597a57d45494e1fc9f34e

**Comment by jensewe** [comment]
`SetExpressionHandler`not declared in `KeyValues` structure. Should be the only issue left.

**Comment by psychonic** [comment]
Good catch. Fixed that as well now. Thanks

**Pull request merged**
