### PR TITLE
Update Windows Protobuf Libraries for VS2019

### PR DESCRIPTION
**Pull request by roflmuffin**
I am building against the CSGO SDK in VS2019 and had to update the libraries for 2019 so I figured I would create a PR for them.

### CODE REVIEW

**Comment by dvander** [comment]
Thanks for the contribution - the source change is fine, but unfortunately due to security concerns around prebuilts (and the inability to audit them), we require prebuilts to originate from either our automated build server or from an official team member.

If you need VS2019 binaries I'd be happy to generate them and get them checked in.

**Comment by roflmuffin** [comment]
Sure that would be great, it would be good to get away from having to use
the fork!

Let me know if you run into issues generating it, I would have run into the
issue before (admittedly I generated the binaries quite a while ago)

**Comment by roflmuffin** [comment]
With regard to the `memalloc.h` change I think I will need to wrap it in some guards so that it only includes the version without the .h extension on VS2019.

**Comment by peace-maker** [comment]
Are you sure you need to rebuild the library? Linking against the prebuilt versions from vs2015 should be fine.

https://github.com/alliedmodders/sourcemod/blob/47c050d5b636d71cecc62b665e3b97fc5d543f3b/core/AMBuilder#L97-L100

**Comment by roflmuffin** [comment]
There doesn't seem to be a compiled library for VS2015 in debug, only release (as far as I can tell), so I get a bunch of mismatch issues when building for debug.

I just tried building in Release using 2019 but targeting the 2015 library and I appear to be getting some unresolved externals from the standard library 🤷, its been a while since I've touched this code so there's a chance I'm doing something wrong.

I'd be grateful for either 2015 debug or 2019 both 👍

**Comment by peace-maker** [comment]
Ah, it's about the debug build. Yes, that is missing in the repo, due to size concerns I guess, maybe @psychonic can give some input. I didn't even notice anymore since I have my own debug build in my local sdk copy :D

**Comment by asherkin** [comment]
Just as an aside until I get around to figuring out LFS, here is a working debug lib for VS2019 + SourceMod - I looked at the one here and spotted that it was built with the wrong runtime mode and had iterator debugging enabled (which was conflicting with SM's build settings).

[libprotobuf.zip](https://github.com/alliedmodders/hl2sdk/files/6835374/libprotobuf.zip)

**Comment by psychonic** [comment]
>  Yes, that is missing in the repo, due to size concerns I guess, maybe @psychonic can give some input.

Size, lack of need in most cases, and most people with the ability to debug having the ability to compile it if they need to. However... looks like we have it there for 2013. I'm not opposed to a 2015 one.

**Pull request closed without merging**
