### PR TITLE
[CS2] Completed collection of entitykeyvalues.cpp, some are reversed, some need simplification

### PR DESCRIPTION
**Pull request by karl-police**
it gotta include entitysystem.h

to access that class there and add stuff to it

https://github.com/alliedmodders/hl2sdk/pull/137#issuecomment-1742214249

### CODE REVIEW

**Comment by karl-police** [comment]
is that list complete https://github.com/alliedmodders/hl2sdk/issues/132


cuz idk
image

**Review by Kenzzer — CHANGES_REQUESTED** [review]
Consider making this PR when there's at least one function reversed, this is going to needlessly create conflicts with other PRs otherwise.

**Comment by karl-police** [comment]
> Consider making this PR when there's at least one function reversed, this is going to needlessly create conflicts with other PRs otherwise.

I have a stroke editing them all cuz I have it not all open in Visual Studio

**Comment by karl-police** [comment]
> Consider making this PR when there's at least one function reversed, this is going to needlessly create conflicts with other PRs otherwise.

There's a fully reversed one now.
ficool2, cleaned it up when they occasionally saw a screenshot on the Discord


I've set up thing now. I also built it, generally the thing builds even if it shouldn't built. But it built.

**Comment by karl-police** [comment]
Merge :D

**Comment by karl-police** [comment]
I put "MISSING_HELP" on stuff so that it can be found through file system searching

some stuff could be simplified, I just got a stroke after doing too much of it


some are too hard to reverse without finding out the other things
and a lot of stuff just has "memory" stuff laying everywhere

**Comment by GAMMACASE** [comment]
Closed in favor of https://github.com/alliedmodders/hl2sdk/pull/183

**Pull request closed without merging**
