### PR TITLE
IVEngineServer2 DisconnectClient

### PR DESCRIPTION
**Pull request by robertnisipeanu**
Tested with a metamod plugin and DisconnectClient works (and the reason is taken into account).

Thanks to `Pisex` for pointing out that DisconnectClient works.

I've also added a comment to the KickClient, as it acts more like BanClient. The client is always kicked with reason 41 (reason argument is ignored) and banned form the server. With DisconnectClient, even when using reason 41, the client only gets kicked.

### CODE REVIEW

**Comment by psychonic** [comment]
I think we should just rename them to KickClient and BanClient. @GAMMACASE thoughts?

**Comment by GAMMACASE** [comment]
In my tests I wasn't even able to get KickClient to work, so unsure, and isn't DisconnectClient name comes from a dwarf binary or a binary with symbols?

**Comment by robertnisipeanu** [comment]
I can rename the KickClient to BanClient, just let me know once you decided how it should be named.

Should I also remove the first unk_xyz method after DisconnectClient, to keep the same amount of functions in the interface?

**Comment by GAMMACASE** [comment]
Also yeah, do remove the unkXXX that goes after since you've added a shift to the vtable rn

**Comment by GAMMACASE** [comment]
Also I've went and verified that the method is called indeed DisconnectClient in the mac binary with symbols, so I'd vote to leave that as is. For the KickClient I guess it could be whatever that suits to what it is doing, if it indeed bans the player (and not only kick with that reason) then sure

**Comment by robertnisipeanu** [comment]
Adjusted the name of KickClient to BanClient.
Removed one method after DisconnectClient and solved conflict with origin

**Comment by GAMMACASE** [comment]
Looks alright to me

**Pull request merged**
