### PR TITLE
S2: Update `IEntityResourceManifestBuilder` interface

### PR DESCRIPTION
**Pull request by Wend4r**
Imported from `Entity Manager` project

### CODE REVIEW

**Comment by GAMMACASE** [comment]
Was the table layout tested on windows as well? Since the unk004 is swapped with ``BuildResourceManifestForEntity`` in your case

**Comment by Wend4r** [comment]
I have works on Windows, using this PR
```c
int iEntityCount = pMyLoading->EntityCount();

const EntitySpawnInfo_t *pEntities = pMyLoading->GetEntities();

for(int i = 0; i < iEntityCount; i++)
{
	g_pGameEntitySystem->BuildResourceManifestForEntity(pEntities[i].m_pEntity->GetClassname(), NULL, s_aEntityManagerProviderAgent.GetMyEntityManifest(), ((EntityManager::CEntitySystemProvider *)g_pGameEntitySystem)->GetKeyValuesMemoryPool());
}
```

**Comment by GAMMACASE** [comment]
Did the exact code worked on linux as well? Asking in case this Unk004 function is named ``BuildResourceManifestForEntity`` too and thus differs per platform due to different signatures

**Comment by GAMMACASE** [comment]
Can you give an insight of the latest commit and why you split virtuals with ifdef? and if it's ready for a review as of now?

**Comment by Wend4r** [comment]
> Can you give an insight of the latest commit and why you split virtuals with ifdef? 

Looking in binary `CEntitySystem` on different OS, `BuildResourceManifest`s are placed in reverse order

> it's ready for a review as of now?

Yes

**Pull request merged**
