### PR TITLE
TF2 win64 + Ambuild tier1/mathlib + long=devil

### PR DESCRIPTION
**Pull request by Kenzzer**
Added compiled version of tier1 and mathlib for win64. I've also taken the liberty of moving the compilation of mathlib/tier1 from makefiles and outdated vcxproj files, to our in-house ambuild.

Just like last time, I'm marking this PR as a draft until tier0 and vstdlib become available when TF2 64 bits is out for windows.

### CODE REVIEW

**Comment by Kenzzer** [comment]
tier0 and vstdlib have been released for windows. I'm currently verifying the compilation of sourcemod, and will mark this PR as ready soon.

**Comment by Kenzzer** [comment]
I was able to obtain a build of sourcemod with this (untested). Marking ready for review

**Comment by drunderscore** [comment]
I cannot add a review comment as you didn't modify this -- but `platform.h`'s 64-bit check is faulty for Windows (and apparently always has been):

https://github.com/alliedmodders/hl2sdk/blob/8cde6861e3a0cce07e61fe90f1a1705c84d5ea4a/public/tier0/platform.h#L145-L149

`__x86_64__` is not defined on MSVC, and pointer definitions following this end up conflicting with the (correct) `steamtypes.h` ones:
https://github.com/alliedmodders/hl2sdk/blob/8cde6861e3a0cce07e61fe90f1a1705c84d5ea4a/public/steam/steamtypes.h#L20-L24

**Comment by Kenzzer** [comment]
> I cannot add a review comment as you didn't modify this -- but `platform.h`'s 64-bit check is faulty for Windows (and apparently always has been):
> 
> https://github.com/alliedmodders/hl2sdk/blob/8cde6861e3a0cce07e61fe90f1a1705c84d5ea4a/public/tier0/platform.h#L145-L149
> 
> `__x86_64__` is not defined on MSVC, and pointer definitions following this end up conflicting with the (correct) `steamtypes.h` ones:
> 
> https://github.com/alliedmodders/hl2sdk/blob/8cde6861e3a0cce07e61fe90f1a1705c84d5ea4a/public/steam/steamtypes.h#L20-L24

If you use the AMBuild scripts
https://github.com/alliedmodders/hl2sdk/blob/8cde6861e3a0cce07e61fe90f1a1705c84d5ea4a/AMBuildScript#L67
I manually add that define in. But I can make one more commit to correct that for standalone compilation

**Comment by drunderscore** [comment]
Ah, I see -- I have a CMake build using this and hadn't had that defined... I think correcting the standalone compilation is worthwhile only because of the inconsistency between `steamtypes.h`, even if it is outdated.

Thanks for noting the AMBuild script defines though!

**Review by psychonic — APPROVED** [review]

**Pull request merged**
