### PR TITLE
tf2: Add vscript headers

### LINKED ISSUE #114: TF2 - Add vscript headers
These can start out as being copied from another branch, and then adjusted as necessary.

### PR DESCRIPTION
**Pull request by Mikusch**
Closes #114

Adds vscript headers and their includes to the tf2 branch, copied from hl2sdk-csgo.

Also bumped `VSCRIPT_INTERFACE_VERSION` to `VScriptManager010`, current version for TF2.

### CODE REVIEW

**Comment by ProjectSky** [comment]
l4d2 has the same version is it possible add to l4d2?

**Review by psychonic — APPROVED** [review]

**Comment by psychonic** [comment]
This is a good start regardless, but did you check TF2's vtable order/list against the header?

**Comment by Mikusch** [comment]
> This is a good start regardless, but did you check TF2's vtable order/list against the header?

I did just now. Looks like all new functions were added at the end of the vtable, except for one, which I've added with the latest commit.

**Comment by psychonic** [comment]
Thanks!

**Comment by peace-maker** [comment]
With this change `stackalloc` is defined twice in tier0/platform.h breaking the build. @Mikusch

**Comment by ambaca** [comment]
@Mikusch 
@peace-maker 

https://github.com/alliedmodders/hl2sdk/commit/9c891b64432ccf2c4646fbbeee71af6b67e55283#commitcomment-94761872

https://github.com/alliedmodders/hl2sdk/commit/9c891b64432ccf2c4646fbbeee71af6b67e55283#r138253913


Linux, **clang version 10.0**, mmsource-1.11, can't compile mmsource **sample_mm** with hl2sdk-tf2 because line 930 error
```
/home/amd/Asiakirjat/alliedmodders/hl2sdk-tf2/public/tier1/utlmemory.h:930:34: error: use of undeclared identifier '_aligned_malloc'; did you mean 'aligned_alloc'?
                CUtlMemory<T>::m_pMemory = (T*)_aligned_malloc( nInitAllocationCount * sizeof(T), nAlignment );
                                               ^~~~~~~~~~~~~~~
                                               aligned_alloc
/usr/include/stdlib.h:586:14: note: 'aligned_alloc' declared here
extern void *aligned_alloc (size_t __alignment, size_t __size)

```

**Pull request merged**
