### PR TITLE
[CS2] update INetChannelInfo and INetChannel, game version: Oct 29 15:38:25

### PR DESCRIPTION
**Pull request by hzqst**
idk if this helps

### CODE REVIEW

**Comment by GAMMACASE** [comment]
Well the formatting is terrible ngl, if you can just update whatever methods were changed and leave every other as is, that's be more helpful!

**Comment by GAMMACASE** [comment]
Can you also remove all the vtable index comments and move normal comments to previous line before the function instead of inlining them (if you've added any, you can leave as is if it was like that)? As currently the diff is still in shambles.

**Comment by hzqst** [comment]
Can you help me fix the copyright symbol `Copyright � 1996-2005` in the first line of the header file? It seems that this symbol is not supported by the local character set on my system.

Additionally, I have updated the args for `INetworkMessageProcessingPreFilter::FilterMessage`, verified by checking the vftable of arg1 (`CNetMessagePB...`) and arg2(`CNetChan`).

**Comment by GAMMACASE** [comment]
Eh, don't worry about that symbol, it's broken like that in a few files already so I don't think that's a big deal (It's also auto replaces itself on my system when I open a file in msvc containing it). Also thanks for changes, I'll do a quick check on them myself and if all is good I'll merge that in.

Can you also tell me how to locate that ``INetworkMessageProcessingPreFilter::FilterMessage``, maybe can you give a sig or string xrefs?

**Comment by hzqst** [comment]
> Eh, don't worry about that symbol, it's broken like that in a few files already so I don't think that's a big deal (It's also auto replaces itself on my system when I open a file in msvc containing it). Also thanks for changes, I'll do a quick check on them myself and if all is good I'll merge that in.
> 
> Can you also tell me how to locate that `INetworkMessageProcessingPreFilter::FilterMessage`, maybe can you give a sig or string xrefs?


I was simply calling `pNetChan->InstallMessageFilter(&g_TestNetFilter);` on an active netchan

```cpp
class CTestNetFilter : public INetworkMessageProcessingPreFilter
{
public:

	bool FilterMessage(const CNetMessage* pData, INetChannel* pChannel) override
	{
		LOG_INFO("FilterMessage m_nCategories=%d, m_MessageId=%d, m_nFlags=%X", 
			pData->GetNetMessage()->GetNetMessageInfo()->m_nCategories,
			pData->GetNetMessage()->GetNetMessageInfo()->m_MessageId,
			pData->GetNetMessage()->GetNetMessageInfo()->m_nFlags);

		return false;
	}
};
CTestNetFilter g_TestNetFilter;
```

**Comment by GAMMACASE** [comment]
Thanks for the pr!

**Pull request merged**
