### PR TITLE
Add voice listen methods to IVEngineServer2

### PR DESCRIPTION
**Pull request by Poggicek**

### CODE REVIEW

**Comment by GAMMACASE** [comment]
Got any comment descriptions explaining what are these doing and what they are for?

**Comment by psychonic** [comment]
These appear to be ported from https://github.com/alliedmodders/hl2sdk/blob/csgo/public/ivoiceserver.h

I think at least copying over the same comment from there would be helpful.

**Comment by psychonic** [comment]
Also, those might be CPlayerSlot now

**Comment by GAMMACASE** [comment]
Ah, also removing the IVoiceServer would be nice as well if it's obsoleted?

**Comment by psychonic** [comment]
> Ah, also removing the IVoiceServer would be nice as well if it's obsoleted?

Yes, good call. I agree.

**Comment by Poggicek** [comment]
yep will do after I attempt implementing a manager and see that everything works as expected

**Comment by Poggicek** [comment]
Should be all good now

**Comment by GAMMACASE** [comment]
@psychonic I assume this would require interfaces.lib rebuild?

**Comment by psychonic** [comment]
> @psychonic I assume this would require interfaces.lib rebuild?

Nope. That one was never handled there. For reference, see `interfaces/interfaces.cpp`

**Review by psychonic — APPROVED** [review]

**Pull request merged**
